const Data = [
  {
    id: 1,
    image: "images",
    title: "Web Developer",
    time: "Now",
    location: "Canada",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iusto necessitatibus, delectus praesentium blanditiis eos ratione incidunt corporis nostrum facilis neque.",
    company: "Novac",
  },
  {
    id: 2,
    image: "images",
    title: "Software Engineer",
    time: "2 hours ago",
    location: "United States",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iusto necessitatibus, delectus praesentium blanditiis eos ratione incidunt corporis nostrum facilis neque.",
    company: "TechCorp",
  },
  {
    id: 3,
    image: "images",
    title: "UX Designer",
    time: "1 day ago",
    location: "United Kingdom",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iusto necessitatibus, delectus praesentium blanditiis eos ratione incidunt corporis nostrum facilis neque.",
    company: "DesignMinds",
  },
  {
    id: 4,
    image: "images",
    title: "Data Scientist",
    time: "3 days ago",
    location: "Australia",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iusto necessitatibus, delectus praesentium blanditiis eos ratione incidunt corporis nostrum facilis neque.",
    company: "DataWorks",
  },
  {
    id: 5,
    image: "images",
    title: "Frontend Developer",
    time: "4 days ago",
    location: "Germany",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iusto necessitatibus, delectus praesentium blanditiis eos ratione incidunt corporis nostrum facilis neque.",
    company: "WebTech",
  },
  {
    id: 6,
    image: "images",
    title: "Backend Developer",
    time: "1 week ago",
    location: "France",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iusto necessitatibus, delectus praesentium blanditiis eos ratione incidunt corporis nostrum facilis neque.",
    company: "CodeCraft",
  },
  {
    id: 7,
    image: "images",
    title: "Full Stack Developer",
    time: "2 weeks ago",
    location: "Japan",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iusto necessitatibus, delectus praesentium blanditiis eos ratione incidunt corporis nostrum facilis neque.",
    company: "ByteLabs",
  },
  {
    id: 8,
    image: "images",
    title: "UI Designer",
    time: "3 weeks ago",
    location: "Spain",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iusto necessitatibus, delectus praesentium blanditiis eos ratione incidunt corporis nostrum facilis neque.",
    company: "PixelGrove",
  },
  {
    id: 9,
    image: "images",
    title: "Product Manager",
    time: "1 month ago",
    location: "Brazil",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iusto necessitatibus, delectus praesentium blanditiis eos ratione incidunt corporis nostrum facilis neque.",
    company: "Prodigy",
  },
  {
    id: 10,
    image: "images",
    title: "QA Engineer",
    time: "2 months ago",
    location: "India",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iusto necessitatibus, delectus praesentium blanditiis eos ratione incidunt corporis nostrum facilis neque.",
    company: "TestMasters",
  },
];

export default Data;
